### ISSUE TITLE
rdfp Adx Echange

### ISSUE THREAD

**Issue by Elrengil** [StevenMMortimer/rdfp#9]
Hi.
How to work with AD_EXCHANGE metric and dimentions?
I get an error when I try to load data
**ReportError.COLUMNS_NOT_SUPPORTED_FOR_REQUESTED_DIMENSIONS**

- example:

request_data <- list(reportJob=list(reportQuery=list(dimensions='AD_EXCHANGE_DATE', 
                                                     dimensions='AD_EXCHANGE_URL',
                                                     dimensions='AD_EXCHANGE_SITE_NAME',
                                                     dimensions='AD_EXCHANGE_PRODUCT_CODE',
                                                     adUnitView='FLAT',
                                                     columns = 'AD_EXCHANGE_AD_REQUESTS',
                                                     columns = 'AD_EXCHANGE_MATCHED_REQUESTS',
                                                     columns = 'AD_EXCHANGE_COVERAGE',
                                                     columns = 'AD_EXCHANGE_CLICKS',
                                                     columns = 'AD_EXCHANGE_AD_REQUEST_CTR',
                                                     columns = 'AD_EXCHANGE_AD_CTR',
                                                     columns = 'AD_EXCHANGE_CPC',
                                                     columns = 'AD_EXCHANGE_MATCHED_ECPM',
                                                     columns = 'AD_EXCHANGE_ESTIMATED_REVENUE',
                                                     columns = 'AD_EXCHANGE_IMPRESSIONS',
                                                     dateRangeType='YESTERDAY'
                                                     
)))

**Comment by StevenMMortimer** [comment]
@elrengil This is an error reported by the API since you have requested a report that is not possible. I recommend two things in trying to troubleshoot: 

First, Log into the DFP User Interface and try to select the same dimensions and metrics. They might be greyed out on the screen which confirms that the combination is not possible. 

Second, check out other resources online. One great location is the DFP help forum: https://productforums.google.com/forum/#!forum/dfp
